apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "High-performance storage for databases and critical applications"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    description: "Standard storage for applications and data"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "Backup storage for long-term retention"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-logs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "Log storage for application and system logs"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain

