version: '3.8'

services:
  scriptoria:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
