apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    name: nexus
    app: runeframeos-nexus
    environment: production
    managed-by: runeframeos
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nexus-quota
  namespace: nexus
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    requests.storage: 50Gi

