# OpenTelemetry Operator Helm Values Configuration
# Security Level: SECURE
# Compliance: NIST CSF, SOC 2

manager:
  # Use contrib collector image for elasticsearchexporter
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: v0.88.0
  
  # Security Configuration
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  
  # Resource Limits
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Pod Security Standards
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  
  # Network Policy
  networkPolicy:
    enabled: true
  
  # Monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
  
  # Logging
  logLevel: info

# RBAC Configuration
rbac:
  create: true
  pspEnabled: true

# Service Account
serviceAccount:
  create: true
  name: opentelemetry-operator

# Webhook Configuration
webhook:
  enabled: true
  port: 9443
  certDir: /tmp/certs
  certName: tls.crt
  keyName: tls.key


