apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    security-level: secure
    compliance: nist-csf
    purpose: certificate-management
    observability: true


