apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    security-level: secure
    compliance: nist-csf
    purpose: observability-backend
    observability: true


