apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    name: opentelemetry
    security-level: secure
    compliance: nist-csf
    purpose: telemetry-collection
    observability: true


