apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
  
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    database: "runeframeos-*"
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.11.0
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "severity"
