apiVersion: apps/v1
kind: Deployment
metadata:
  name: runeweaver
  namespace: runeframeos
  labels:
    app: runeweaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runeweaver
  template:
    metadata:
      labels:
        app: runeweaver
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: runeweaver
        image: runeweaver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3008
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3008"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Health checks disabled for initial testing
        # livenessProbe: [ADD_LATER]
        # readinessProbe: [ADD_LATER]
---
apiVersion: v1
kind: Service
metadata:
  name: runeweaver
  namespace: runeframeos
  labels:
    app: runeweaver
spec:
  selector:
    app: runeweaver
  ports:
  - port: 3008
    targetPort: 3008
    nodePort: 30011
    protocol: TCP
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runeweaver-ingress
  namespace: runeframeos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: runeweaver.pedantictheory.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: runeweaver
            port:
              number: 3008
