apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: postgresql
type: Opaque
data:
  # Base64 encoded passwords (generate with: echo -n "password" | base64)
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  runeframeos-password: cnVuZWZyYW1lb3NfcGFzc3dvcmQ=  # runeframeos_password
  replication-password: cmVwbGljYXRpb25fcGFzc3dvcmQ=  # replication_password
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-certs
  namespace: postgresql
type: Opaque
data:
  # SSL certificates (base64 encoded) - placeholder values
  server.crt: <base64-encoded-cert>
  server.key: <base64-encoded-key>
  ca.crt: <base64-encoded-ca>

