apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-sa
  namespace: postgresql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresql-role
  namespace: postgresql
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-rolebinding
  namespace: postgresql
subjects:
- kind: ServiceAccount
  name: postgresql-sa
  namespace: postgresql
roleRef:
  kind: Role
  name: postgresql-role
  apiGroup: rbac.authorization.k8s.io

